// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Org.Product.Infrastructure.Repositories;

#nullable disable

namespace Org.Product.Infrastructure.Repositories.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260915073048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Org.Product.Domain.Entities.Account.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int?>("CreatorLevel")
                        .HasColumnType("integer")
                        .HasColumnName("creator_level");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_deleted");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("SoftDeleted")
                        .HasDatabaseName("ix_role_soft_deleted");

                    b.HasIndex("Name", "SoftDeleted")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name_soft_deleted");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8df3280-8ab1-4b45-8d6a-6c3e669317ac"),
                            Code = "developer",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "developer with all cathable resources even it was obselete",
                            Level = 0,
                            Name = "developer",
                            Order = 0,
                            SoftDeleted = false,
                            State = false
                        },
                        new
                        {
                            Id = new Guid("4fe6ebb8-5001-40b4-a59e-d193ad9186f8"),
                            Code = "super",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "super user with all catchable resources",
                            Level = 0,
                            Name = "super",
                            Order = 0,
                            SoftDeleted = false,
                            State = false
                        },
                        new
                        {
                            Id = new Guid("e1f23f37-919c-453b-aff1-1214415e54b8"),
                            Code = "admin",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "admin to manage user resourcs",
                            Level = 0,
                            Name = "admin",
                            Order = 0,
                            SoftDeleted = false,
                            State = false
                        },
                        new
                        {
                            Id = new Guid("4a15f57a-0cb7-4cc9-95c0-91ba672a341c"),
                            Code = "member",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "normal user with some basic resources",
                            Level = 0,
                            Name = "member",
                            Order = 0,
                            SoftDeleted = false,
                            State = false
                        },
                        new
                        {
                            Id = new Guid("ffce17eb-a74c-4b44-aaac-2e2e78e04f9e"),
                            Code = "visitor",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "a visitor with some read resources",
                            Level = 0,
                            Name = "visitor",
                            Order = 0,
                            SoftDeleted = false,
                            State = false
                        });
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Account.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int?>("CreatorLevel")
                        .HasColumnType("integer")
                        .HasColumnName("creator_level");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nick")
                        .HasColumnType("text")
                        .HasColumnName("nick");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Passphrase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passphrase");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("register_time");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_deleted");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("SoftDeleted")
                        .HasDatabaseName("ix_user_soft_deleted");

                    b.HasIndex("Username", "SoftDeleted")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username_soft_deleted");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8ba3a6d-c7b1-4d90-b0c9-66f1cbd66101"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "unknow",
                            Gender = 2,
                            Nick = "initial-developer",
                            Order = 0,
                            Passphrase = "Uh+8E9ft9jptdMzAVRKo0UYQtqn5epsbJUZQGbL/Xhk=",
                            PhoneNumber = "unknow",
                            RegisterTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salt = "5+fPPv0FShtKo3ed746TiuNojEZsxuPkhbU+YvF5DuQ=",
                            SoftDeleted = false,
                            State = false,
                            Username = "developer"
                        },
                        new
                        {
                            Id = new Guid("a8ba3a6d-c7b1-4d90-b0c9-66f1cbd66102"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "unknow",
                            Gender = 2,
                            Nick = "initial-super",
                            Order = 0,
                            Passphrase = "WSAcdSAvzQFUq3iXLWXLmcuPmWHIjE8ffSBTVjJVBPQ=",
                            PhoneNumber = "unknow",
                            RegisterTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salt = "aY68cuKZh+LNfYczaGclgtTOYy34yvl1O/H9IX3bBtU=",
                            SoftDeleted = false,
                            State = false,
                            Username = "super"
                        },
                        new
                        {
                            Id = new Guid("a8ba3a6d-c7b1-4d90-b0c9-66f1cbd66103"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "unknow",
                            Gender = 2,
                            Nick = "initial-admin",
                            Order = 0,
                            Passphrase = "Lc8DL5jIpDxDfsDp6gYk2HjVIEzXZ30MJc5eW6OU6ko=",
                            PhoneNumber = "unknow",
                            RegisterTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salt = "JO3wh7gOTUQ5cBydCoQqnazvw5dgRoVQkNpdrIAvVgI=",
                            SoftDeleted = false,
                            State = false,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Account.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Authority.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int?>("CreatorLevel")
                        .HasColumnType("integer")
                        .HasColumnName("creator_level");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean")
                        .HasColumnName("favorite");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsLink")
                        .HasColumnType("boolean")
                        .HasColumnName("is_link");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_deleted");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<bool>("Visiable")
                        .HasColumnType("boolean")
                        .HasColumnName("visiable");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_code");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_permission_order");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_permission_parent_id");

                    b.ToTable("permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9df3280-8ab1-4b45-8d6a-6c3e669317ac"),
                            Code = "root",
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "root menu",
                            Favorite = false,
                            IsLink = false,
                            Name = "Root",
                            Order = 0,
                            SoftDeleted = false,
                            State = false,
                            Type = 0,
                            Visiable = true,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Authority.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permission_role_id");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Account.User", b =>
                {
                    b.OwnsOne("Org.Product.Domain.ValueObjects.UserValue.UserDetail", "Detail", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("AboutMe")
                                .HasColumnType("text")
                                .HasColumnName("about_me");

                            b1.Property<int>("Gender")
                                .HasColumnType("integer")
                                .HasColumnName("gender");

                            b1.HasKey("UserId")
                                .HasName("pk_user_detail");

                            b1.ToTable("user_detail");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_detail_user_user_id");

                            b1.Navigation("User");
                        });

                    b.OwnsOne("Org.Product.Domain.ValueObjects.UserValue.UserSetting", "Settings", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("language");

                            b1.HasKey("UserId")
                                .HasName("pk_user_setting");

                            b1.ToTable("user_setting");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_setting_user_user_id");

                            b1.Navigation("User");
                        });

                    b.Navigation("Detail");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Account.UserRole", b =>
                {
                    b.HasOne("Org.Product.Domain.Entities.Account.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("Org.Product.Domain.Entities.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Authority.Permission", b =>
                {
                    b.HasOne("Org.Product.Domain.Entities.Authority.Permission", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_permission_permission_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Org.Product.Domain.Entities.Authority.RolePermission", b =>
                {
                    b.HasOne("Org.Product.Domain.Entities.Authority.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("Org.Product.Domain.Entities.Account.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
